# Generated by Django 5.2.4 on 2025-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('product_info', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
