# Generated by Django 5.2.4 on 2025-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
